services:
  neraca:
    image: ghcr.io/vigarp/neraca:latest
    container_name: neraca
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      - PORT=8088
      - DB_PATH=/app/data/neraca.db
      - ENV=production
      - TZ=Asia/Jakarta
    networks:
      - edge_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.neraca.rule=Host(`neraca.vigarp.web.id`)"
      - "traefik.http.routers.neraca.entrypoints=websecure"
      - "traefik.http.routers.neraca.tls=true"
      - "traefik.http.routers.neraca.tls.certresolver=letsencrypt"
      - "traefik.http.routers.neraca.middlewares=security-headers@file"
      - "traefik.http.services.neraca.loadbalancer.server.port=8088"

networks:
  edge_network:
    external: true

